config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  get 'group/:group_id/invite/new' => 'group_invites#new', as: :new_group_invite
  post 'group/:group_id/invite' => 'group_invites#create', as: :create_group_invite
  get 'group/:group_id/invite/:id' => 'group_invites#show', as: :group_invite

  resources :private_messages

  resources :groups do
    resources :player
    resources :posts do
      resources :post_segments
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :players
  has_many :group_invites
  has_many :posts
  belongs_to :user

  validates :name, presence: true
end

app/models/group_invite.rb
class GroupInvite < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user_id, presence: {with: true, message: "Recipient's Account not found"}
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :name, uniqueness: {scope: :group_id}
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_segments
  belongs_to :group

  validates :title, presence: true
end

app/models/post_segment.rb
class PostSegment < ActiveRecord::Base
  belongs_to :post

  validates :subject, presence: true
end

app/models/posts.rb
class Posts < ActiveRecord::Base
  has_many :post_segments

  validates :title, presence: true
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: {with: true, message: "Recipient's Account not found"}
  validates :subject, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :players
  has_many :groups
  has_many :private_messages
  has_many :group_invites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'pp'
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def mp *splat
    puts "#"*50
    splat.each do |item|
      pp item
    end
    puts "#"*50
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
    group = Group.find_by(id: params[:group_id])
    @character = group.characters.new(group_id: group.id)
  end

  def create
    invite_id = params[:invite_id].keys.first
    invite = GroupInvite.find_by(id: invite_id)

    @character = current_user.characters.new(character_params)
    @character.group_id = params[:group_id]
    if @character.save
      invite.destroy
      redirect_to group_path(params[:group_id]), notice: "Character Created Succesfully"
    else
      render :new
    end
  end

  private
  def character_params
    params.require(:character).permit(
      :name,
      :race,
      :money,
      :exp,
      :level
    )
  end
end

app/controllers/group_invites_controller.rb
class GroupInvitesController < ApplicationController
  def new
    @invite = GroupInvite.new
    group_name = Group.find_by(id: params[:group_id]).name

    @default_msg =  "Hello, I am inviting you to #{group_name}.\n"+
                    "Please click the link and create a character."
  end

  def create
    recipient = User.find_by(email: params[:recipient])

    if recipient
      user_id = recipient.id
    end

    @invite = GroupInvite.new({
      message: params[:group_invite][:message],
      group_id: params[:group_id],
      user_id: user_id,
    })

    if @invite.save
      redirect_to group_path(params[:group_id]), notice: "Invite Sent"
    else
      render :new
    end
  end

  def show
    @invite = GroupInvite.find_by(id: params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    players = current_user.players

    @groups = {}
    @groups[:player] = players.map {|player| player.group}
    @groups[:owner] = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    group = current_user.groups.new(group_params)

    if group.save
      redirect_to group, notice: 'Group was created'
    else
      render :new
    end
  end

  def edit
    @group = Group.find_by(id: params[:id])
  end

  def update
    group = Group.find_by(id: params[:id])

    if group.update(group_params)
      redirect_to group, notice: 'Group was updated'
    else
      redirect_to edit_group_path(group)
    end
  end

  def show
    @group = Group.find_by(id: params[:id])
    @group_owner = User.find_by(id: @group.user_id)
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def new
    group = Group.find_by(id: params[:group_id])
    @player = group.players.new()

  end

  def create
    invite_id = params[:invite_id].keys.first
    invite = GroupInvite.find_by(id: invite_id)

    @character = current_user.players.new(player_params)
    @character.group_id = params[:group_id]
    if @character.save
      invite.destroy
      redirect_to group_path(params[:group_id]), notice: "Character Created Succesfully"
    else
      render :new
    end
  end

  def show
    @player = Player.find_by(id: params[:id])
  end

  private
  def player_params
    params.require(:player).permit(
      :name,
      :race,
      :money,
      :exp,
      :level,
      :gender,
      :game_class
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    group = Group.find_by(id: params[:group_id])
    @post = group.posts.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to group_post_path(group, @post), notice:"Post saved"
    else
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @post_segments = @post.post_segments.order(created_at: :asc)
    toggle_post_segment_visable if params[:visable]
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to group_post_path(@post.group, @post), notice:"Post updated"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to @post.group, notice:"Post deleted"

  end

  private
  def post_params
    params.require(:post).permit(:title, :visable)
  end

  def toggle_post_segment_visable
    segment = PostSegment.find_by(id: params[:segment])
    segment.update_attribute(:visable, params[:visable])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_invites_helper.rb
module GroupInvitesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/post_segments_helper.rb
module PostSegmentsHelper
end

app/helpers/posts_controller_helper.rb
module PostsControllerHelper
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/group_invites/new.html.erb
<h1>Invite New Member</h1>

<% if @invite.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

    <ul>
    <% @invite.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @invite, url: create_group_invite_path do |f| %>
  <%= text_field_tag :recipient, nil, placeholder:"Recipient's Email" %>

  <%= f.label "Message" %>
  <%= f.text_area :message, value:@default_msg %>
  <%= f.submit "Send Invite" %>
<% end %>

app/views/group_invites/show.html.erb
<h1>Invite to Join <%= @invite.group.name %></h1>
<strong>Sent: <%= @invite.created_at %></strong>
<p>
  <%= @invite.message %>
</p>
<%= link_to "Join Group", new_group_player_path(@invite.group_id, {invite_id: @invite.id}) %>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= f.text_field :name, placeholder: "Group Name" %>
  <%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>
<%= render "form" %>

app/views/groups/index.html.erb
<h1 class="ui header">Groups</h1>

<h3>Game Master</h3>
<div class="ui divided list">
  <% @groups[:owner].each do |group| %>
    <div class="item">
      <i class="icon"><%= group.players.length %></i>
      <div class="content">
        <%= link_to group[:name], group_path(group), class:"header" %>
        <div class="description truncate">stuff</div>
      </div>
    </div>
  <% end %>
</div>

<h3>Player</h3>
<div class="ui divided list">
<% @groups[:player].each do |group| %>
  <div class="item">
    <i class="icon"><%= group.players.length %></i>
    <div class="content">
      <%= link_to group[:name], group_path(group), class:"header"%>
      <div class="description truncate">
        <% group.players.each do |player| %>
          <% if player.user_id == current_user.id %>
            <strong><%= "#{player.level}-#{player.name}" %></strong>
          <% else %>
            <%= "#{player.level}-#{player.name}" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/groups/new.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>

app/views/groups/show.html.erb
<%= link_to "Edit Group", edit_group_path %>

<h1> <%= @group.name %> </h1>
<h3> <%= @group_owner.email %> </h3>
<p>
  created: <%= @group.created_at %>
</p>

<h3>Members</h3>
<%= link_to "Invite", new_group_invite_path(@group) %>

<% @group.players.each do |player| %>
  <p>
    <%= link_to player.name, group_player_path(@group.id, player.id) %>
  </p>
<% end %>

<h3>Posts</h3>
<%= link_to "New Post", new_group_post_path(@group) %>
<% @group.posts.each do |post| %>
  <p>
    <%= link_to post.title, group_post_path(@group, post) %>
  </p>
<% end %>

app/views/player/new.html.erb
<h1>Create Character for <%= @player.group.name %></h1>

<% if @player.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@player.errors.count, "error") %> prohibited this character from being saved:</h2>

    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @player, url: "/groups/#{params[:group_id]}/player" do |f| %>
  <%= hidden_field :invite_id, params[:invite_id] %>
  <%= f.text_field :name, placeholder:"name" %>
  <%= f.text_field :race, placeholder:"race" %>
  <%= f.text_field :game_class, placeholder:"class" %>
  <%= f.text_field :gender, placeholder:"gender" %>
  <%= f.text_field :money, placeholder:"money" %>
  <%= f.number_field :exp, placeholder:"experiance" %>
  <%= f.number_field :level, placeholder:"level" %>
  <%= f.submit %>
<% end %>

app/views/player/show.html.erb
<h1><%= @player.name %></h1>
<h3>Race: <%= @player.race %></h3>
<h3>Class: <%= @player.game_class %></h3>

<strong>Level: <%= @player.level %></strong>
<strong>Experiance: <%= @player.exp %></strong>
<strong>Money: <%= @player.money %></strong>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post, url:group_post_path(@post.group, @post) do |f| %>
  <%= f.text_field :title, placeholder:"title" %>

  <%= f.label :visable %>
  <%= f.check_box :visable %>

  <%= f.submit %>
<% end %>

<%= link_to 'Delete', group_post_path(@post.group, @post), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post, url:group_posts_path do |f| %>
  <%= f.text_field :title, placeholder:"title" %>

  <%= f.label :visable %>
  <%= f.check_box :visable %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= link_to "edit post", edit_group_post_path(@post.group, @post) %>
<%= link_to "Add Segment", new_group_post_post_segment_path(@post.group, @post) %>

<% @post_segments.each do |segment| %>
  <ul>
    <li>
      <h3><%= segment.subject %></h3>
      <% if segment.visable %>
        <%= link_to "Hide", group_post_path(@post.group, @post, {segment:segment.id, visable:"false"}) %>
      <% else %>
        <%= link_to "Show", group_post_path(@post.group, @post, {segment:segment.id, visable:"true"}) %>
      <% end %>
      <p>
        <%= segment.body %>
      </p>
      <%= link_to "edit segment", edit_group_post_post_segment_path(@post.group, @post, segment) %>
    </li>

  </ul>
<% end %>