config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  get 'group/:group_id/invite/new' => 'group_invites#new', as: :new_group_invite
  post 'group/:group_id/invite' => 'group_invites#create', as: :create_group_invite
  get 'group/:group_id/invite/:id' => 'group_invites#show', as: :group_invite

  resources :private_messages

  resources :groups do
    resources :player
    resources :posts do
      resources :post_segments
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :players
  has_many :group_invites
  has_many :posts
  belongs_to :user

  validates :name, presence: true
end

app/models/group_invite.rb
class GroupInvite < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user_id, presence: {with: true, message: "Recipient's Account not found"}
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :name, uniqueness: {scope: :group_id}
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_segments
  belongs_to :group

  validates :title, presence: true
end

app/models/post_segment.rb
class PostSegment < ActiveRecord::Base
  belongs_to :post

  validates :subject, presence: true
end

app/models/posts.rb
class Posts < ActiveRecord::Base
  has_many :post_segments

  validates :title, presence: true
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: {with: true, message: "Recipient's Account not found"}
  validates :subject, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :players
  has_many :groups
  has_many :private_messages
  has_many :group_invites
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    players = current_user.players

    @groups = {}
    @groups[:player] = players.map {|player| player.group}
    @groups[:owner] = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    group = current_user.groups.new(group_params)

    if group.save
      redirect_to group, notice: 'Group was created'
    else
      render :new
    end
  end

  def edit
    @group = Group.find_by(id: params[:id])
  end

  def update
    group = Group.find_by(id: params[:id])

    if group.update(group_params)
      redirect_to group, notice: 'Group was updated'
    else
      redirect_to edit_group_path(group)
    end
  end

  def show
    @group = Group.find_by(id: params[:id])
    @group_owner = User.find_by(id: @group.user_id)
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def new
    group = Group.find_by(id: params[:group_id])
    @player = group.players.new()

  end

  def create
    invite_id = params[:invite_id].keys.first
    invite = GroupInvite.find_by(id: invite_id)

    @character = current_user.players.new(player_params)
    @character.group_id = params[:group_id]
    if @character.save
      invite.destroy
      redirect_to group_path(params[:group_id]), notice: "Character Created Succesfully"
    else
      render :new
    end
  end

  def show
    @player = Player.find_by(id: params[:id])
  end

  private
  def player_params
    params.require(:player).permit(
      :name,
      :race,
      :money,
      :exp,
      :level,
      :gender,
      :game_class
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    group = Group.find_by(id: params[:group_id])
    @post = group.posts.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to group_post_path(group, @post), notice:"Post saved"
    else
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @post_segments = @post.post_segments.order(created_at: :asc)
    toggle_post_segment_visable if params[:visable]
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to group_post_path(@post.group, @post), notice:"Post updated"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to @post.group, notice:"Post deleted"

  end

  private
  def post_params
    params.require(:post).permit(:title, :visable)
  end

  def toggle_post_segment_visable
    segment = PostSegment.find_by(id: params[:segment])
    segment.update_attribute(:visable, params[:visable])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_invites_helper.rb
module GroupInvitesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/post_segments_helper.rb
module PostSegmentsHelper
end

app/helpers/posts_controller_helper.rb
module PostsControllerHelper
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RPGLog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= "notice: #{flash[:notice]}" if flash[:notice]%>
<%= "alert: #{flash[:alert]}" if flash[:alert]%>


<div class="main-container">

  <div class="ui grid">
    <div class="three wide column"><%= render partial: "shared/sidebar" %></div>
    <div class="thirteen wide column">
      <div class="ui segment">
        <%= yield %>
      </div>
    </div>
  </div>
</div>


</body>
</html>

app/views/shared/_login_controls.html.erb
<% if current_user %>
  Welcome <%= current_user.email %>
  <div class="menu">
    <%= link_to raw("Sign Out <i class='unlock alternate icon'></i>"), destroy_user_session_path, class:"item", method: :delete %>
  </div>
<% else %>

  <i class="lock icon"></i> Welcome
  <div class="menu">
    <%= link_to "Sign Up", new_user_registration_path, class:"item" %>
    <%= link_to "Sign In", new_user_session_path, class:"item" %>
  </div>

<% end %>

app/views/shared/_menu_groups.html.erb
<% if current_page?(groups_path) %>
  <div class="item">
    <i class="users icon"></i> Groups
    <div class="menu">
      <%= link_to "New Group", new_group_path, class:"item" %>
      <!--<a class="active item">Search</a>
      <a class="item">Add</a>
      <a class="item">Remove</a>-->
    </div>
  </div>
<% else %>
  <%= link_to raw("<i class='users icon'></i>Groups"), groups_path, class:"item" %>
<% end %>

app/views/shared/_menu_messages.html.erb
<% if current_page?(private_messages_path) %>

  <div class="item">
    <i class="mail icon"></i> Inbox

    <div class="menu">
      <%= link_to "New Message", new_private_message_path, class:"item" %>
      <!--<a class="active item">Search</a>-->
      <!--<a class="item">Remove</a>-->
    </div>
  </div>

<% else %>
  <%= link_to raw("<i class='mail icon'></i>Inbox"), private_messages_path, class:"item" %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="ui vertical menu">
  <div class="item">
    <%= render partial: "shared/login_controls" %>
  </div>

  <% if current_user %>
    <%= render partial: "shared/menu_messages" %>
    <%= render partial: "shared/menu_groups" %>
  <% end %>


  <!--<div class="ui dropdown item">
    More
    <i class="dropdown icon"></i>
    <div class="menu">
      <a class="item"><i class="edit icon"></i> Edit Profile</a>
      <a class="item"><i class="globe icon"></i> Choose Language</a>
      <a class="item"><i class="settings icon"></i> Account Settings</a>
    </div>
  </div> -->
</div>